---
abstract: 'Perl interface to the Embedly API'
author:
  - 'Jason Wieland <jwieland@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Embedly
requires:
  Any::Moose: 0
  HTTP::Headers: 0
  HTTP::Response: 0
  JSON: 0
  LWP::UserAgent: 0
  Ouch: 0
  Regexp::Common: 0
  Test::Mock::LWP::Dispatch: 0
  Test::More: 0.88
  URI::Escape: 0
  parent: 0
resources:
  bugtracker: https://github.com/jwieland/embedly-perl/issues
  homepage: http://search.cpan.org/dist/WebService-Embedly/
  repository: git://github.com/jwieland/embedly-perl.git
version: 0.10
